name: Publicar imagen en Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    name: Publicar imagen en Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: pytest tests.py

    - name: Construir imagen de la aplicación
      run: docker build -t testeandoloco-py .

    - name: Iniciar sesión en Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Etiquetar la imagen
      run: docker tag testeandoloco-py ${{ secrets.DOCKERHUB_USERNAME }}/testeandoloco-py:latest

    - name: Publicar imagen en Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/testeandoloco-py:latest

