name: Publicar imagen en Docker Hub

on:
  workflow_run:
    workflows: ["Construir imagen de la aplicación"]
    types:
      - completed

jobs:
  publish-docker-image:
    name: Publicar imagen en Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Test Build docker image final
        run: |
          docker build -t testeandoloco-py  .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_TOKEN }}"
          docker tag testeandoloco-py ${{ secrets.DOCKERHUB_USERNAME }}/testeandoloco-py 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/testeandoloco-py
